baseURL = 'https://techtrailpulse.com/'
locale = 'en-us'
title = 'Tech Trail Pulse'
theme = 'blowfish'
enableRobotsTXT = true
disableKinds = ['taxonomy', 'term']

[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true

[outputs]
	home = ['HTML', 'RSS', 'JSON']

[params]
	colorScheme = 'blowfish'
	defaultAppearance = 'light'
	autoSwitchAppearance = true
	defaultSocialImage = 'img/site-social-preview-1200x630.jpg'
	enableSearch = true
	enableCodeCopy = false
	Logo = 'favicon.PNG'
	mainSections = ['posts']
	copyright = '&copy; { year } Greg Christian - [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)'

[params.author]
	image = 'img/GregMemorialDay2026.png'

[params.header]
	layout = 'basic'

[params.footer]
	showMenu = false
	showCopyright = true
	showThemeAttribution = true
	showAppearanceSwitcher = true
	showScrollToTop = true

[params.homepage]
	layout = 'page'
	showRecent = true
	showRecentItems = 18
	cardView = true
	cardViewScreenWidth = false

[params.article]
	showBreadcrumbs = false
	showTableOfContents = false
	showTaxonomies = false
	showAuthor = false

[[menu.main]]
	name = 'Home'
	pageRef = '/'
	weight = 10

[[menu.main]]
	name = 'About'
	pageRef = '/about/'
	weight = 15

[[menu.main]]
	name = 'Reading Trail'
	pageRef = '/reading-list/'
	weight = 20

[[menu.main]]
	name = 'Puzzlemania'
	pageRef = '/puzzlemania/'
	weight = 30
